<?php

namespace WordPressExtendCore\RestRoute;

use WordPressExtendCore\AbstractClass\RestRoute\Register;
use WordPressExtendCore\WordPressExtendCore;
use WP_Query;
use WP_REST_Request;

class Articles extends Register
{
    const ROUTE = 'articles';
    const NAME_SPACE = WordPressExtendCore::HOOK_NAME;

    public static function getInstance(string $namespace = self::NAME_SPACE, string $route = self::ROUTE, string $className = __CLASS__, int $version = 2): Register
    {
        return parent::getInstance($namespace, $route, $className, $version); // TODO: Change the autogenerated stub
    }

    public function response(WP_REST_Request $Request): mixed
    {
        // TODO: Implement response() method.
        /** @var WP_Query $articles */
        $articles = new WP_Query([
            'post_type' => 'any',
            'post_status' => ['publish'],
            'posts_per_page' => -1
        ]);

        if ($articles->have_posts()) {
            return $articles->get_posts();
        }

        return [];
    }
}
